services:
  - type: web
    name: da-crise-ao-chamado-api
    runtime: node
    plan: free
    rootDir: apps/api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: WEB_ORIGIN
        value: https://da-crise-ao-chamado-web.onrender.com
      - key: WEBHOOK_SECRET
        sync: false
      - key: GG_WEBHOOK_SECRET
        sync: false
      - key: GG_PRODUCT_MAP
        sync: false
      - key: GG_CHECKOUT_LINKS
        sync: false
      - key: ADMIN_KEY
        sync: false

  - type: web
    name: da-crise-ao-chamado-web
    runtime: node
    plan: free
    rootDir: apps/web
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: WEB_PORT
        value: 10000
