export const products = [
  {
    id: "cookies-basico",
    slug: "cookies-basico",
    title: "Cookies",
    description: "Fundamentos para produzir e vender cookies com padrao profissional.",
    tagline: "Plano Basico",
    level: "Basico",
    runtime: "Trilha principal",
    category: "Cookies",
    cover: "/cards/cookie-lucrativo.jpg",
    price: 97,
    hasCheckout: true
  },
  {
    id: "cookies-pro",
    slug: "cookies-pro",
    title: "Cookies",
    description: "Estrategia completa de producao, precificacao e escala.",
    tagline: "Plano Pro",
    level: "Pro",
    runtime: "Trilha avancada",
    category: "Cookies",
    cover: "/cards/cookie-lucrativo.jpg",
    price: 197,
    hasCheckout: true
  },
  {
    id: "cookies-upsell",
    slug: "cookies-upsell",
    title: "Cookies",
    description: "Pacote de upgrade com recursos extras de venda e margem.",
    tagline: "Plano Upsell",
    level: "Upsell",
    runtime: "Bonus premium",
    category: "Cookies",
    cover: "/cards/cookie-lucrativo.jpg",
    price: 147,
    hasCheckout: true
  },
  {
    id: "brownie-basico",
    slug: "brownie-basico",
    title: "Brownie",
    description: "Receitas e operacao para comecar seu negocio de brownie.",
    tagline: "Plano Basico",
    level: "Basico",
    runtime: "Trilha principal",
    category: "Brownie",
    cover: "/cards/brownie-lucrativo.jpg",
    price: 97,
    hasCheckout: true
  },
  {
    id: "brownie-pro",
    slug: "brownie-pro",
    title: "Brownie",
    description: "Metodo completo para aumentar lucro e escala de producao.",
    tagline: "Plano Pro",
    level: "Pro",
    runtime: "Trilha avancada",
    category: "Brownie",
    cover: "/cards/brownie-lucrativo.jpg",
    price: 197,
    hasCheckout: true
  },
  {
    id: "brownie-upsell",
    slug: "brownie-upsell",
    title: "Brownie",
    description: "Upgrade com materiais extras para acelerar resultado.",
    tagline: "Plano Upsell",
    level: "Upsell",
    runtime: "Bonus premium",
    category: "Brownie",
    cover: "/cards/brownie-lucrativo.jpg",
    price: 147,
    hasCheckout: true
  },
  {
    id: "palha-italiana-basico",
    slug: "palha-italiana-basico",
    title: "Palha Italiana",
    description: "Base completa para criar, precificar e vender palha italiana.",
    tagline: "Plano Basico",
    level: "Basico",
    runtime: "Trilha principal",
    category: "Palha Italiana",
    cover: "/cards/palha-italiana-lucrativa.jpg",
    price: 97,
    hasCheckout: true
  },
  {
    id: "palha-italiana-pro",
    slug: "palha-italiana-pro",
    title: "Palha Italiana",
    description: "Escala e posicionamento premium para aumentar ticket medio.",
    tagline: "Plano Pro",
    level: "Pro",
    runtime: "Trilha avancada",
    category: "Palha Italiana",
    cover: "/cards/palha-italiana-lucrativa.jpg",
    price: 197,
    hasCheckout: true
  },
  {
    id: "palha-italiana-upsell",
    slug: "palha-italiana-upsell",
    title: "Palha Italiana",
    description: "Complemento com tecnicas extras para vender mais por dia.",
    tagline: "Plano Upsell",
    level: "Upsell",
    runtime: "Bonus premium",
    category: "Palha Italiana",
    cover: "/cards/palha-italiana-lucrativa.jpg",
    price: 147,
    hasCheckout: true
  },
  {
    id: "doces-no-pote-basico",
    slug: "doces-no-pote-basico",
    title: "Doces no Pote",
    description: "Comece com receitas certeiras e processo simplificado.",
    tagline: "Plano Basico",
    level: "Basico",
    runtime: "Trilha principal",
    category: "Doces no Pote",
    cover: "/cards/doce-no-pote-lucrativo.jpg",
    price: 97,
    hasCheckout: true
  },
  {
    id: "doces-no-pote-pro",
    slug: "doces-no-pote-pro",
    title: "Doces no Pote",
    description: "Metodo pro para elevar padrao, margem e recorrencia.",
    tagline: "Plano Pro",
    level: "Pro",
    runtime: "Trilha avancada",
    category: "Doces no Pote",
    cover: "/cards/doce-no-pote-lucrativo.jpg",
    price: 197,
    hasCheckout: true
  },
  {
    id: "doces-no-pote-upsell",
    slug: "doces-no-pote-upsell",
    title: "Doces no Pote",
    description: "Upsell com tecnicas de aumento de ticket e fidelizacao.",
    tagline: "Plano Upsell",
    level: "Upsell",
    runtime: "Bonus premium",
    category: "Doces no Pote",
    cover: "/cards/doce-no-pote-lucrativo.jpg",
    price: 147,
    hasCheckout: true
  },
  {
    id: "mini-bolo-vulcao-basico",
    slug: "mini-bolo-vulcao-basico",
    title: "Mini Bolo Vulcao",
    description: "Base tecnica para produzir mini bolos com acabamento premium.",
    tagline: "Plano Basico",
    level: "Basico",
    runtime: "Trilha principal",
    category: "Mini Bolo Vulcao",
    cover: "/cards/mini-bolo-vulcao-lucrativo.jpg",
    price: 97,
    hasCheckout: true
  },
  {
    id: "mini-bolo-vulcao-pro",
    slug: "mini-bolo-vulcao-pro",
    title: "Mini Bolo Vulcao",
    description: "Escala, vendas e posicionamento para faturamento recorrente.",
    tagline: "Plano Pro",
    level: "Pro",
    runtime: "Trilha avancada",
    category: "Mini Bolo Vulcao",
    cover: "/cards/mini-bolo-vulcao-lucrativo.jpg",
    price: 197,
    hasCheckout: true
  },
  {
    id: "mini-bolo-vulcao-upsell",
    slug: "mini-bolo-vulcao-upsell",
    title: "Mini Bolo Vulcao",
    description: "Pacote de upgrade com recursos extras para diferenciar oferta.",
    tagline: "Plano Upsell",
    level: "Upsell",
    runtime: "Bonus premium",
    category: "Mini Bolo Vulcao",
    cover: "/cards/mini-bolo-vulcao-lucrativo.jpg",
    price: 147,
    hasCheckout: true
  },
  {
    id: "iogurte-gourmet-pro",
    slug: "iogurte-gourmet-pro",
    title: "Iogurte Gourmet",
    description: "Produto bonus para aumentar mix e recorrencia de clientes.",
    tagline: "Order Bump",
    level: "Pro",
    runtime: "Entregavel bonus",
    category: "Order Bump",
    cover: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80",
    price: null,
    hasCheckout: false
  },
  {
    id: "geladinho-gourmet-pro",
    slug: "geladinho-gourmet-pro",
    title: "Geladinho Gourmet",
    description: "Oferta complementar para aumentar ticket na compra principal.",
    tagline: "Order Bump",
    level: "Pro",
    runtime: "Entregavel bonus",
    category: "Order Bump",
    cover: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=80",
    price: null,
    hasCheckout: false
  },
  {
    id: "recheio-sem-fogo-pro",
    slug: "recheio-sem-fogo-pro",
    title: "Recheio Sem Fogo",
    description: "Tecnicas adicionais para elevar valor percebido do cardapio.",
    tagline: "Order Bump",
    level: "Pro",
    runtime: "Entregavel bonus",
    category: "Order Bump",
    cover: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=1200&q=80",
    price: null,
    hasCheckout: false
  },
  {
    id: "massa-confeitaria-pro",
    slug: "massa-confeitaria-pro",
    title: "Massa de Confeitaria",
    description: "Aplicativo complementar para ampliar portfolio de produtos.",
    tagline: "Order Bump",
    level: "Pro",
    runtime: "Entregavel bonus",
    category: "Order Bump",
    cover: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=1200&q=80",
    price: null,
    hasCheckout: false
  }
];


